### ISSUE TITLE
Mapping documentation is not very clear

### ISSUE THREAD

**Issue by beyerz** [Pierstoval/EntityMerger#1]
Firstly, well done for the library, I have found it relatively straightforward and has been very helpful.

I had to go through the whole flow in order to understand how the mapping array should be presented. 

I would suggest creating a helper function that we can send property name and the serialized name and get the mapping back.

I would also suggest a helper that uses JMS metadata to automap.

If I get some time, I will put something together for a pull request.

**Comment by Pierstoval** [comment]
I'd like to avoid coupling with JMS as I this is quite an overhead. This package is sort of compatible, but I don't want to go further.

For the mapping, it's simple: if you populate the `$mapping` argument, it'll correspond to the list of properties to hydrate, allowing you to specify the object name (as opposed to the name in the argument, that can be different, especially if you handle underscores differently).

I can write docs sometimes, or if you've read the code and now understand it, you may do a PR :)

Just know that I stopped using this library in my personal projects because it was quite unsatisfying, in terms of performances and flexibility (I know do everything by-hand instead of relying on custom hydrators like this lib). But it's still nice for simple stuff 👍

**Comment by beyerz** [comment]
I think that this library could be very useful and with a little effort, you could go back to using it.

would you consider changing the architecture slightly?

I think that the serializer and entity manager were provided using an adapter pattern, then we could easily separate the logic and not enforce the use of JMS as well as allow other Object Managers other than doctrine, without affecting the core logic of the merger? 

I know that this would grow the library somewhat, but it would also allow anyone the freedom to write their own adapters as required by their system.

**Comment by Pierstoval** [comment]
Not sure this project would encounter massive adoption, merging objects is a tough task and people might need to populate data in their objects in several ways. This is, for example, the reason why we have serializers, hydrators (in Doctrine) or simply `JsonSerializable` interface 😉.

Maybe I can consider taking a look at your needs first: what does your application need at the moment with this package? If we can solve it, it'll be faster than changing the whole architecture right now :)

**Comment by beyerz** [comment]
My use case is as follows:

I have a patch option in my rest api to do partial updates on my entities.
I use the json input together with JMS deserialize to create a temporary entity with the changes.
I then load the original entity from db and use the merge function to update the entity.
Finally I push this entity back into my db.

My serialized names do not always match the property name so I stepped into using the mapping.
Sometimes, my patch can include more than one parameter and not all of my parameters need to be mapped. But the merger has an all or nothing concept when it comes to dealing with the mapping.

In any case, I put together a helper function on my side that builds the map for me using the JMS entity metadata and all works fine. I do feel however that this process could be far more efficient.

In any case, my issue is resolved with this workaround, but I did feel that this library is useful and wanted to give some feedback.

If I get a chance, I will add to the documentation about the mapping structure.

**Comment by Pierstoval** [comment]
> I use the json input together with JMS deserialize to create a temporary entity with the changes.
> I then load the original entity from db and use the merge function to update the entity.

You see, that's the reason why I think this package is not worth it: this isn't the way you should populate your object.

Instead, you should choose between:

* Retrieve your object, and deserialize the JSON _into_ this object. With Symfony's serializer, it's possible by adding the `'object_to_populate' => $object` option when deserializing.
* Use a FormType to populate a DTO with the submitted json-decoded data, and when the DTO is valid, update your entity with the DTO, with a method such as `$entity->updateFromPatch($dto)`
* Manually decode the JS and populate your object with the data, and then validate your entity (but it could lead to an invalid entity state, so it's not recommended).

The problem mostly comes from the fact that you have a `PATCH` method that does a _partial_ update, which is not easy to manage. In this case, it means that if a key is not present in the JSON, you should **not** update it in your object. Even this package doesn't do everything for you, unless you soecify the `mapping` option, but even then it's not the best option.

You'd better end up with something like this:

```php
foreach ($jsonDecodedData as $key => $value) {
    $entity->updateField($key, $value);
}
```

As long as you can have validation over the specified field, you'll be ok, and it'll be way more performant and flexible than using this package

**Comment by beyerz** [comment]
Thanks for the feedback and suggestions on the best way to do this.
I feel that this concept should be very similar to filling a Symfony form that was prepopulated, and has its own option for validations. Basically your suggested point 2. 

Thanks

**Comment by Pierstoval** [comment]
> I feel that this concept should be very similar to filling a Symfony form that was prepopulated, and has its own option for validations. Basically your suggested point 2.

Exactly, that's why it's a better solution to use already existing components for this: a Symfony form + a DTO, and you're set :)
